[package]
name = "tokei-now"
version = "0.1.0"
authors = ["Mathspy <mathspy257@gmail.com>"]
edition = "2018"

[dependencies]
git2 = "0.8"
http = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.*"
tokei = "10.*"
url = "1.*"

[[bin]]
name = "tokei-now"
path = "index.rs"
